### PR TITLE
Port to Godot 4

### PR DESCRIPTION
**Pull request by OmarShehata**
Copies the updated addon from https://github.com/godot-extended-libraries/godot-antialiased-line2d/pull/8 and used the Godot 4 auto project converter. Everything seems to work automatically, didn't have to do manual changes.

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks for undertaking this porting effort!

I've tested this PR locally. On 4.2.dev c495eb510 (Linux/Forward+), there are some visual issues that don't occur in the Godot 3.x version:

image

There are some "holes" in geometry and the example line on the right lost its default blue color (that one should be easy to fix).

These change appearance (but don't disappear) at higher resolutions when using the `canvas_items` stretch mode:

Screenshot_20230819_224950

Compare this with the 3.x appearance in 3.5.2 (which, to be fair has regressed compared to [earlier versions](https://raw.githubusercontent.com/Calinou/media/master/godot-antialiased-line2d-demo/screenshot.png)…):

image

I've tested Godot 3.3.4, 3.4, 3.4.4, 3.5, 3.5.1 and 3.5.2 and they all exhibit this issue, even at the same resolution as the [earlier versions](https://raw.githubusercontent.com/Calinou/media/master/godot-antialiased-line2d-demo/screenshot.png) screenshot:

Screenshot_20230819_225942

I've tried checking out ccdd3dbf752e5ecccd016e4bcd0b727222b741da locally, so this is not caused by https://github.com/godot-extended-libraries/godot-antialiased-line2d/pull/4.

I've changed graphics card since I took the screenshot last year, but I'm still on a NVIDIA graphics card on Linux. I'm not sure why anything would change with regards to mipmap selection in the driver (this is pretty much set in stone nowadays).

PS: You forgot to change the stretch mode to `canvas_items` in the Project Settings (which is the new name of the `2d` stretch mode in 4.x).

**Comment by OmarShehata** [comment]
> I've tested this PR locally. On 4.2.dev c495eb510 (Linux/Forward+), there are some visual issues that don't occur in the Godot 3.x version:

Ah yeah, I am able to reproduce these visual artifacts. I also noticed similar behavior in the 3.x version, and assumed it must be an issue on my end and not the result of the port....

**Comment by Calinou** [comment]
I found a way to improve line texture appearance a lot: enable anisotropic filtering on the Line2D/Polygon2D's properties, and set anisotropic filtering level to 16× in the Project Settings (not required, but further improves quality).

I don't know exactly why this is required, but either way, it helps and shouldn't be too costly in terms of performance in a 2D project.

**Comment by Calinou** [comment]
Merged manually with https://github.com/godot-extended-libraries/godot-antialiased-line2d-demo/commit/0a4a948a8094c13307c6f52ce501a5dd3117e9b2. Thanks!

**Pull request closed without merging**
